[package]
name = "ll-game"
version = "0.1.0"
edition = "2021"

[dependencies]
glutin = "*"    # Windowing (+++ Rust)
glium = "*"     # Graphics  (+/- Rust)
cpal = "*"      # Audio     (+++ Rust)
ocl = "*"       # Computing (+/- Rust)
