* Atividade Pratica!

** (1) Lista
É uma atividade pratica.
 - [[https://www.cin.ufpe.br/~garme/public/(ebook)Estruturas%20de%20Dados%20Usando%20C%20(Tenenbaum).pdf][Estruturas de Dados Usando C]]

** Referências de C
 - [[https://www.gnu.org/software/libc/manual/html_node/][The GNU C Library]]
 - [[https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.html][The GNU C Reference Manual]]
 - [[https://gcc.gnu.org/onlinedocs/gcc/C-Implementation.html][C Implementation-Defined Behavior]]

** Ferramentas
 - [[https://godbolt.org/][Compiler Explorer]]

* (1) Lista - Lista de Projetos

Após mais uma derrota na cara do Joãozinho, ele decidiu dar um "tempo"...  
Enquanto isso, você terá um "tempo" para fazer uns projetinhos que você quer fazer. Como você não sabe quais dos projetos vai começar a fazer, acabou decidindo que vai criar um projeto que te ajudará a escolher qual projeto fazer. E, obviamente, esse projeto é uma "Lista de Projetos". Como você ainda não é o arquimago da computação, você decidiu fazer uma versão "beta" desse projeto, já que ele será bem limitado inicialmente.

Essa Lista de Projetos terá as seguintes funcionalidades:
	*1.* Adicionar um projeto no começo da lista.
	*2.* Pegar um projeto no final da lista, o que irá eventualmente remover esse mesmo projeto da lista.

Em suma, você está criando uma pilha de projetos, já que a ideia se baseia no fato de que grande parte dos seus projetos são uma porcaria, e você só os fez porque não parou para pensar direito. Logo, agora, com essa restrição, você irá pensar muito antes de fazer ou descartar um projeto.

A funcionalidade ~2~ não é equivalente a fazer o projeto, já que a ação de executar cabe a você mesmo. Essa funcionalidade basicamente serve para retirar o projeto que, em tese, seria feito. Só que você pode ou não realizá-lo, já que ele pode ser um projeto ruim.

* Comando de Compilação

** Shell
#+BEGIN_SRC sh
gcc -O3 -std=c17 <arquivos *.c> -o <executável>
#+END_SRC

** Make
#+BEGIN_SRC makefile
default:
	gcc -O3 -std=c17 <arquivos *.c> -o <executável>
#+END_SRC
